---
fail_fast: false
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        # Based off of https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines
        args: ["build", "ci", "docs", "feat", "fix", "perf", "refactor", "style", "test"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.0
    hooks:
      - id: clang-format
        files: >
          (?x)^(
            ^components/|
            ^src/
          )
        types_or: [ "c++", "c", "header" ]
